spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tech_app?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: myuser

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update